### ISSUE TITLE
SSKR URs Not Typed

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/URVault-iOS#26]
SSKRs seem not to be typed. We should add that.

![image](https://user-images.githubusercontent.com/1110886/117886696-4da6cb00-b24b-11eb-8815-2d2cc5ef3874.png)

**Comment by Fonta1n3** [comment]
hmm seems the underlying library URKit is rejecting that UR, is it possible it is from v1.0.0 UR?

**Comment by Fonta1n3** [comment]
I would suggest using the latest build of Gordian Guardian to derive your SSKR shards and trying again as that is working for me.

**Comment by Fonta1n3** [comment]
This seems to be a UR that was created with the old version of UR as I the URKit library does not recognize it as valid. The app does indeed recognize any valid ur. Closing this as that seems to be the issue.

**Comment by shannona** [comment]
It was actually brand-new from Gordian Guardian. Perhaps it was invalid because it was generated as a 1 of 1?

**Comment by Fonta1n3** [comment]
Ah, strange, will need to raise this on the URKit repo.

**Comment by Fonta1n3** [comment]
> It was actually brand-new from Gordian Guardian. Perhaps it was invalid because it was generated as a 1 of 1?

Im able to add one of one just fine from Guardian.

@wolfmcnally any idea why the following code would fail on the above SSKR ur?

```
if let ur = try? URDecoder.decode(processed) {
        return ur.type
 }
```

**Comment by shannona** [comment]
I double-checked to be sure I wasn't misremembering.

Process:
(1) Goto Guardian
(2) Choose the Test Seed
(3) Generate an SSKR as 1 with threshold of 1
(4) Copy
(5) Use the Paste into URVault function

(same result: it's untyped.)

**Comment by Fonta1n3** [comment]
> I double-checked to be sure I wasn't misremembering.
> 
> Process:
> (1) Goto Guardian
> (2) Choose the Test Seed
> (3) Generate an SSKR as 1 with threshold of 1
> (4) Copy
> (5) Use the Paste into URVault function
> 
> (same result: it's untyped.)

ah the issue was a newline in the QR code, condensing whitespaces on the string fixes it. closing for now.
