### ISSUE TITLE
More Types

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/URVault-iOS#27]
We need to add more label types, and @shannona and I need docs on updating them in the code.

Related, if a label is added in a future release, old "unknown" labels need to be updated, or a button in settings to rescan labels.

Starting a list of more types of QRs here:

* Microsoft Authenticator: `ms-msa://code=`

**Comment by Fonta1n3** [comment]
+1 for giving an example! please provide examples and I will happily add them

**Comment by ChristopherA** [comment]
@ShannonA — what should the "unknown" type be? `unknown`? `blank`? `text`?

**Comment by ChristopherA** [comment]
At minimum we should support labelling the schemes that Apple directly supports with handers: https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/Introduction/Introduction.html

Here are some common QRs that I've found in the wild that are supported by 3rd party QR apps:

* location: `https://maps.google.com/maps?` & `http://maps.apple.com/?q=`
* website: `https:` `http:`
* url: `urlto:` (these don't have https or https — not sure why it exists, but it is common)
* email: `mailto:`
* vcard: `BEGIN:VCARD`
* mecard: `mecard:`
* bizcard: `bizcard:
* event: `BEGIN:VEVENT`
* phone: `tel:`
* sms:  `sms:`, `smsto:`, `mms:` & `mmsto:`
* feed: `feed:`
* facetime video `facetime:`
* facetime audio `facetime-audio:`
* wifi `wifi:`
* ios app: `https://itunes.apple.com/`

**Comment by shannona** [comment]
I think "unknown" is good for the unknown stuff.

**Comment by shannona** [comment]
A few others I stumbled upon while testing the Vault out:

bitcoin: [bitcoin address]
payto: [https://datatracker.ietf.org/doc/html/rfc8905]
iban: [International Bank Account Number?]
text without any prefix [that's probably genuinely unknown]

**Comment by Fonta1n3** [comment]
Latest commit adds all of these types 👍🏻
