### ISSUE TITLE
QR, Lifehash Display Fail for an account map

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/URVault-iOS#29]
I've been scanning random QR codes I have sitting about, and for one of them, an account map, I get a weird error.

It looks fine if I look at the full info:

![image](https://user-images.githubusercontent.com/1110886/117887589-aaef4c00-b24c-11eb-86ef-09e108b37f52.png)

But if I try to look at the QR with that button, it spins forever:

![image](https://user-images.githubusercontent.com/1110886/117887631-bcd0ef00-b24c-11eb-8fd3-f036faa30284.png)

It also seems to be the only QR that I've saved that didn't generate a Lifehash:

![image](https://user-images.githubusercontent.com/1110886/117888207-7af47880-b24d-11eb-844b-1491fdcf4389.png)

**Comment by Fonta1n3** [comment]
should be fixed now
