### ISSUE TITLE
Tweak Summary to fit longer Label

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/URVault-iOS#36]
![image](https://user-images.githubusercontent.com/69103/117924820-33043e80-b2ab-11eb-99fc-baafe24e11ac.png)

I'd really like the label to run all the way across — as you can see, nothing fits.

The qr and > buttons could be a little higher, and the date lower, and the label fit between them all the way across. Maybe even one notch smaller in size?

**Comment by Fonta1n3** [comment]
<img width="546" alt="Screen Shot 2021-05-13 at 10 40 47" src="https://user-images.githubusercontent.com/30832395/118070060-d2265480-b3d7-11eb-935c-cb9c0a315739.png">

is that acceptable?
