### ISSUE TITLE
Minimum Sorting Methodology

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/URVault-iOS#39]
I think that sorting remains the largest usability challenge for UR Vault. I would suggest the following minimal sorting methodology for the release:

(1) Do a first-level sort alphabetical by type
(2) Do a second-level sort alphabetical by name

No frills beyond that, like choosing sorting methods, choosing sorting by hand, etc. Just this minimal methodology.

This subsumes #7 and #8.

A more complex sorting methodology in the future could allow drag sorting per #37, could enable the user to choose between different sorting methodologies, or could use submenus for each type, but this is probably what's necessary for release usability.

**Comment by Fonta1n3** [comment]
This is done as per #40, leaving open in case more options are desired.
