### ISSUE TITLE
Allow CR in labels

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/URVault-iOS#42]
![image](https://user-images.githubusercontent.com/69103/118078822-c8670780-b36b-11eb-99aa-6a1d1f4c42d6.png)

As you can see in this screenshot, I really like how the line wrap works so I can have the account name on the second line.

However, you can't force this, for instance, if I try to add a return after Mainnet to force (Titania MacBook Pro) to the 2nd line it will not let me add it.

**Comment by Fonta1n3** [comment]
hmm not sure the best way to do this. it is standard that UITextField and UITextView do not allow the user to add newlines with the return button.

 do you have an example of this sort of UI in another app? 

The only way I think this makes sense is by adding a sub label.
